2021-11-15 21:55:38,617 — Main application — ERROR — The received packet do not begin with a valid header!
Traceback (most recent call last):
  File "main_app.py", line 94, in <module>
    Fingerprint_Access_exit()
  File "/home/pi/Desktop/Phase_Two_Code_03_11_2021/Firmware/FingerprintActivation.py", line 305, in Fingerprint_Access_exit
    if ( fingerprint_scanner_exit.readImage() == True ):
  File "/home/pi/Desktop/Phase_Two_Code_03_11_2021/Firmware/fingerprint.py", line 664, in readImage
    receivedPacket = self.__readPacket()
  File "/home/pi/Desktop/Phase_Two_Code_03_11_2021/Firmware/fingerprint.py", line 302, in __readPacket
    raise Exception('The received packet do not begin with a valid header!')
Exception: The received packet do not begin with a valid header!
