2021-12-12 04:45:43,265 — Main application — ERROR — The received packet do not begin with a valid header!
Traceback (most recent call last):
  File "main_app.py", line 93, in <module>
    Fingerprint_Access()
  File "/home/pi/Desktop/Phase_Two_Code_03_11_2021/Firmware/FingerprintActivation.py", line 283, in Fingerprint_Access
    if ( fingerprint_scanner.readImage() == True ):
  File "/home/pi/Desktop/Phase_Two_Code_03_11_2021/Firmware/fingerprint.py", line 664, in readImage
    receivedPacket = self.__readPacket()
  File "/home/pi/Desktop/Phase_Two_Code_03_11_2021/Firmware/fingerprint.py", line 302, in __readPacket
    raise Exception('The received packet do not begin with a valid header!')
Exception: The received packet do not begin with a valid header!
